# VERSION 0.01
#
# Node.js app container for the farmer's market app

FROM mattselph/nodejs

MAINTAINER Matt Selph <matt.selph@gmail.com> | github.com/mattselph

WORKDIR /opt/app
RUN git clone https://github.com/mattselph/mattselphcom.git


