# VERSION 0.03
#
# Container for the farmer's market app

FROM mattselph/nodejs

MAINTAINER Matt Selph <matt.selph@gmail.com> | github.com/mattselph

#WORKDIR /opt/app/mattselphcom
#RUN git pull /home/mselph/Documents/mattselphcom.git
#RUN git checkout express

CMD ["node","/opt/app/mattselphcom/fmkt/app.js"]

