# VERSION 0.01
#
# App + Webserver with python and Flask 0.10.1 
# on Ubuntu 14.04 LTS (Trusty Tahr)
#

FROM ubuntu:14.04
MAINTAINER Matt Selph <matt.selph@gmail.com> | github.com/mattselph	

# install python, pip, Flask, and pymongo
RUN apt-get update && apt-get install -y python-all python-pip
RUN pip install Flask pymongo
